const urls = [
    { name: 'Sales Bill', url: '/new-sales-bill' },
    { name: 'Modify Sales Bill', url: '/modify-sales-bill' },
    { name: 'Cancel Sales Bill', url: '/cancel-sales-bill' },
    { name: 'Reprint Sales Bill', url: '/print-sales-bill' },
    { name: 'Purchase Entry', url: '/new-purchase-entry' },
    { name: 'Modify Purchase Entry', url: '/modify-purchase-entry' },
    { name: 'Cancel Purchase Entry', url: '/cancel-purchase-entry' },
    { name: 'Reprint Purchase Entry', url: '/print-purchase-entry' },
    { name: 'Product', url: '/new-product' },
    { name: 'Sales Estimate', url: '/new-sales-estimate' },
    { name: 'Modify Sales Estimate', url: '/modify-sales-estimate' },
    { name: 'Cancel Sales Estimate', url: '/cancel-sales-estimate' },
    { name: 'Customer Order Form', url: '/customer-order-form' },
    { name: 'List Order Form', url: '/list-order-form' },
    { name: 'Sales Enquiry', url: '/sales-enquiry' },
    { name: 'Sales Item Enquiry', url: '/sales-item-enquiry' },
    { name: 'Purchase Enquiry', url: '/purchase-enquiry' },
    { name: 'Purchase Item Enquiry', url: '/purchase-item-enquiry' },
    { name: 'Purchase Return', url: '/new-purchase-return' },
    { name: 'Modify Purchase Return', url: '/modify-purchase-return' },
    { name: 'Cancel Purchase Return', url: '/cancel-purchase-return' },
    { name: 'Reprint Purchase Return', url: '/print-purchase-return' },
    { name: 'Purchase Return Enquiry', url: '/purchase-return-enquiry' },
    { name: 'Sales Return', url: '/new-sales-return' },
    { name: 'Modify Sales Return', url: '/modify-sales-return' },
    { name: 'Cancel Sales Return', url: '/cancel-sales-return' },
    { name: 'Reprint Sales Return', url: '/print-sales-return' },
    { name: 'Sales Return Enquiry', url: '/sales-return-enquiry' },
    { name: 'Damaged Stock', url: '/new-damaged-stock' },
    { name: 'Modify Damaged Stock', url: '/modify-damaged-stock' },
    { name: 'Cancel Damaged Stock', url: '/cancel-damaged-stock' },
    { name: 'Damaged Stock List', url: '/damaged-stock-list' },
    { name: 'Purchase Order', url: '/purchase-order'}
]

export default urls;